name: Snyk Security CI/CD

on: push

jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions@0.3.0
      with: 
       command: test
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions@0.3.0
      with: 
       command: code test
      continue-on-error: true # To make sure that SARIF upload gets called
      env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
